### ISSUE TITLE
Investigate effects of disabling hyperthreading

### ISSUE THREAD

**Issue by jvc56** [jvc56/MAGPIE#165]
My dad mentioned that we should look into this.

**Comment by olaugh** [comment]
just tried it on my mac and magpie autoplay is definitely slower with hyperthreading disabled

**Comment by olaugh** [comment]
<img width="898" alt="Screenshot 2024-03-03 at 10 00 50 PM" src="https://github.com/jvc56/MAGPIE/assets/57605/199ff3b6-14aa-4556-8373-b2238013f179">

**Comment by jvc56** [comment]
Thanks for checking. Sounds like we should keep that enabled.

**Comment by jvc56** [comment]
I misunderstood what Vince was saying. He speculated that disabling hyperthreading would improve _single threaded_ performance, though in practice there should be no reason to not use all available cores. I guess cores might be blocking on memory accesses which allows the hyperthreading to continue to run other pipelines in the CPU? I don't think any of this is actionable though, just wanted to make a note of it.

**Comment by olaugh** [comment]
ok, that sounds more plausible. fwiw i just tried
time bin/magpie-fast-math go autoplay lex CSW21 s1 equity s2 equity r1 best r2 best numplays 1 gp rs 1337 threads 1 i 1000
with and without hyperthreading and it didn't make a difference for me
