### ISSUE TITLE
build errors on windows platform

### ISSUE THREAD

**Issue by ik4u** [jvc56/MAGPIE#264]
ik4u@P920X MINGW64 ~
$ cd C:/Users/ik4u/Downloads/MAGPIE-main

ik4u@P920X MINGW64 ~/Downloads/MAGPIE-main
$ make magpie BUILD=release
cc -O3 -flto -funroll-loops -march=native -Wall -Wno-trigraphs -DBOARD_DIM=15 -DRACK_SIZE=7 -c src/ent/autoplay_results.c -o obj/src/ent/autoplay_results.o
In file included from src/ent/letter_distribution.h:14:0,
                 from src/ent/bag.h:7,
                 from src/ent/game.h:9,
                 from src/ent/autoplay_results.h:8,
                 from src/ent/autoplay_results.c:1:
src/ent/../util/log.h:37:18: error: missing binary operator before token "("
 #if __has_builtin(__builtin_unreachable)
                  ^
In file included from src/ent/player.h:6:0,
                 from src/ent/game.h:12,
                 from src/ent/autoplay_results.h:8,
                 from src/ent/autoplay_results.c:1:
src/ent/klv.h:7:20: fatal error: endian.h: No such file or directory
 #include <endian.h>
                    ^
compilation terminated.
make: *** [Makefile:69: obj/src/ent/autoplay_results.o] Error 1

**Comment by jvc56** [comment]
Thanks for trying to compile on Windows and making an issue! You're probably the first to try MAGPIE on Windows, so we appreciate your patience! I've started #266 which should hopeful take care of this issue. I don't have a Windows machine on hand, so feel free to try it out and comment with any further compile errors that come up.

**Comment by ik4u** [comment]
Dear Friend
Thank you for the prompt response and for opening issue #266! I’m excited to contribute to this project and help refine it further.

As a retired English teacher and avid Scrabble player, I have a particular interest in language-based projects like MAGPIE. I’m also eager to contribute my ideas and be part of the beta testing process. With a powerful workstation equipped with the latest Xeon Platinum processors, as well as a Threadripper workstation, I’m well-prepared to handle any computing tasks involved in testing or compiling.

One idea I’d like to share involves the inference algorithm. While it’s helpful when the opponent is a perfect player, I believe it could be even more useful if it analyzed not only the current state of play but also incorporated data from all of the opponent’s past moves. This could reveal patterns or tendencies in their strategy, giving the inference algorithm a more comprehensive understanding of their playstyle.

Looking forward to testing the next version and contributing further!

Keep up the good work!
Ahmed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
