### ISSUE TITLE
perf_test_multithread_sim fails on MacOS

### ISSUE THREAD

**Issue by jvc56** [jvc56/MAGPIE#40]
Not totally sure what's causing this, but it might be the float comparisons of zero in compare_simmed_plays are acting differently on different hardware.

**Comment by domino14** [comment]
`./run sim 4` or whatever number of threads is broken on master; 62d4c759c512772c6f0154411104e5d76ba7ab50 is the first bad commit

**Comment by jvc56** [comment]
The failure of ./run sim 4 was unrelated. This error is about the perf_test_multithread_sim test when run by the unit tests invoked by './run u' on MacOS
