### ISSUE TITLE
highest possible equity values per anchors from shadow play don't take preendgame and endgame adjustments into account 

### ISSUE THREAD

**Issue by olaugh** [jvc56/MAGPIE#75]
I noticed while working on #73 that some plays recorded surpass their anchor's theoretical max from shadow play. Preendgame heuristic and outplay adjustment are known in shadow play because they only depend on play length. Non-outplay endgame plays should give the most optimistic value, assuming the play keeps the lowest possible scoring tiles.

As more heuristics are added, we can still try to keep the anchors' max equities valid by always taking the optimistic view.

**Comment by jvc56** [comment]
oof, thanks for catching this! The consequences of my not writing unit tests for anchors has emerged. I'll make an issue to write unit tests.
